import { Lead, Opportunity, Activity, Account, Contact } from "@shared/schema";

// Demo user ID - this would normally come from auth
export const DEMO_USER_ID = "demo-user-gareth";

export const demoAccounts: Omit<Account, "id" | "createdAt">[] = [
  {
    name: "Peterson & Associates",
    website: "https://peterson-llc.com",
    industry: "Legal Services",
    phone: "(555) 123-4567",
    address: "123 Main St, Business District",
    ownerId: DEMO_USER_ID,
  },
  {
    name: "Metro Property Group",
    website: "https://metroprop.com",
    industry: "Real Estate",
    phone: "(555) 234-5678",
    address: "456 Commercial Ave, Downtown",
    ownerId: DEMO_USER_ID,
  },
  {
    name: "Riverside Manufacturing",
    website: "https://riverside-mfg.com",
    industry: "Manufacturing",
    phone: "(555) 345-6789",
    address: "789 Industrial Blvd, Riverside",
    ownerId: DEMO_USER_ID,
  },
  {
    name: "ABC Heating Solutions",
    website: "https://abcheating.com",
    industry: "HVAC Services",
    phone: "(555) 456-7890",
    address: "321 Service Road, Uptown",
    ownerId: DEMO_USER_ID,
  },
  {
    name: "Central Shopping Mall",
    website: "https://centralmall.com",
    industry: "Retail/Commercial",
    phone: "(555) 567-8901",
    address: "555 Mall Drive, Central City",
    ownerId: DEMO_USER_ID,
  },
];

export const demoContacts: Omit<Contact, "id" | "createdAt">[] = [
  {
    firstName: "Michael",
    lastName: "Peterson",
    email: "m.peterson@peterson-llc.com",
    phone: "(555) 123-4567",
    title: "Managing Partner",
    accountId: "account-1",
    ownerId: DEMO_USER_ID,
  },
  {
    firstName: "Sarah",
    lastName: "Wilson",
    email: "s.wilson@metroprop.com",
    phone: "(555) 234-5678",
    title: "Property Manager",
    accountId: "account-2",
    ownerId: DEMO_USER_ID,
  },
  {
    firstName: "David",
    lastName: "Chen",
    email: "d.chen@riverside-mfg.com",
    phone: "(555) 345-6789",
    title: "Facilities Director",
    accountId: "account-3",
    ownerId: DEMO_USER_ID,
  },
];

export const demoLeads: Omit<Lead, "id" | "createdAt">[] = [
  {
    firstName: "Michael",
    lastName: "Peterson",
    email: "m.peterson@peterson-llc.com",
    phone: "(555) 123-4567",
    company: "Peterson & Associates",
    title: "Managing Partner",
    source: "Referral",
    status: "New",
    ownerId: DEMO_USER_ID,
    notes: "Interested in HVAC maintenance contract for their office building.",
    tags: ["hvac", "commercial", "high-value"],
  },
  {
    firstName: "Sarah",
    lastName: "Wilson",
    email: "s.wilson@metroprop.com",
    phone: "(555) 234-5678",
    company: "Metro Property Group",
    title: "Property Manager",
    source: "Website",
    status: "Qualified",
    ownerId: DEMO_USER_ID,
    notes: "Managing multiple commercial properties, needs comprehensive facility management.",
    tags: ["facility-management", "multi-property"],
  },
  {
    firstName: "David",
    lastName: "Chen",
    email: "d.chen@riverside-mfg.com",
    phone: "(555) 345-6789",
    company: "Riverside Manufacturing",
    title: "Facilities Director",
    source: "Cold Call",
    status: "Proposal",
    ownerId: DEMO_USER_ID,
    notes: "Industrial plumbing upgrade needed urgently.",
    tags: ["industrial", "plumbing", "urgent"],
  },
  {
    firstName: "Jennifer",
    lastName: "Martinez",
    email: "j.martinez@techstartup.com",
    phone: "(555) 678-9012",
    company: "Tech Startup Inc",
    title: "Office Manager",
    source: "Website",
    status: "New",
    ownerId: DEMO_USER_ID,
    notes: "New office space needs complete HVAC installation.",
    tags: ["hvac", "new-construction"],
  },
];

export const demoOpportunities: Omit<Opportunity, "id" | "createdAt">[] = [
  {
    name: "Peterson & Associates HVAC Contract",
    accountId: "account-1",
    contactId: "contact-1",
    leadId: "lead-1",
    amount: 25000,
    stage: "New",
    probability: 30,
    closeDate: new Date("2025-01-30"),
    ownerId: DEMO_USER_ID,
    description: "Annual HVAC maintenance contract for office building",
    nextAction: "Send detailed proposal",
    nextActionDate: new Date("2025-01-15"),
  },
  {
    name: "Metro Property Group Facility Management",
    accountId: "account-2",
    contactId: "contact-2",
    leadId: "lead-2",
    amount: 85000,
    stage: "Qualified",
    probability: 60,
    closeDate: new Date("2025-02-15"),
    ownerId: DEMO_USER_ID,
    description: "Comprehensive facility management for 5 commercial properties",
    nextAction: "Schedule site visits",
    nextActionDate: new Date("2025-01-20"),
  },
  {
    name: "Riverside Manufacturing Plumbing Upgrade",
    accountId: "account-3",
    contactId: "contact-3",
    leadId: "lead-3",
    amount: 125000,
    stage: "Proposal",
    probability: 75,
    closeDate: new Date("2025-01-25"),
    ownerId: DEMO_USER_ID,
    description: "Complete industrial plumbing system upgrade",
    nextAction: "Present final proposal",
    nextActionDate: new Date("2025-01-22"),
  },
  {
    name: "Central Shopping Mall HVAC Overhaul",
    accountId: "account-5",
    contactId: null,
    leadId: null,
    amount: 275000,
    stage: "Proposal",
    probability: 50,
    closeDate: new Date("2025-03-01"),
    ownerId: DEMO_USER_ID,
    description: "Complete HVAC system replacement for shopping mall",
    nextAction: "Technical review meeting",
    nextActionDate: new Date("2025-01-30"),
  },
  {
    name: "ABC Heating Solutions Partnership",
    accountId: "account-4",
    contactId: null,
    leadId: null,
    amount: 45000,
    stage: "Won",
    probability: 100,
    closeDate: new Date("2024-12-15"),
    ownerId: DEMO_USER_ID,
    description: "Residential service contract partnership",
    nextAction: "Contract execution",
    nextActionDate: new Date("2025-01-10"),
  },
];

export const demoActivities: Omit<Activity, "id" | "createdAt">[] = [
  {
    type: "Call",
    subject: "Called Peterson & Associates",
    description: "Discussed HVAC maintenance contract renewal. Follow-up needed with detailed proposal.",
    leadId: "lead-1",
    contactId: "contact-1",
    opportunityId: "opportunity-1",
    accountId: "account-1",
    ownerId: DEMO_USER_ID,
    dueDate: null,
    completed: true,
  },
  {
    type: "Email",
    subject: "Email sent to Riverside Manufacturing",
    description: "Proposal for industrial plumbing upgrade project with technical specifications.",
    leadId: "lead-3",
    contactId: "contact-3",
    opportunityId: "opportunity-3",
    accountId: "account-3",
    ownerId: DEMO_USER_ID,
    dueDate: null,
    completed: true,
  },
  {
    type: "Note",
    subject: "New lead: Metro Property Group",
    description: "Commercial facility management opportunity for multiple properties. High value potential.",
    leadId: "lead-2",
    contactId: "contact-2",
    opportunityId: null,
    accountId: "account-2",
    ownerId: DEMO_USER_ID,
    dueDate: null,
    completed: true,
  },
  {
    type: "Task",
    subject: "Follow up with ABC Heating",
    description: "Check on contract execution status and next steps.",
    leadId: null,
    contactId: null,
    opportunityId: "opportunity-5",
    accountId: "account-4",
    ownerId: DEMO_USER_ID,
    dueDate: new Date("2025-01-12"),
    completed: false,
  },
  {
    type: "Task",
    subject: "Send proposal to Downtown Office",
    description: "Prepare and send detailed HVAC proposal for new office space.",
    leadId: "lead-4",
    contactId: null,
    opportunityId: null,
    accountId: null,
    ownerId: DEMO_USER_ID,
    dueDate: new Date("2025-01-14"),
    completed: false,
  },
  {
    type: "Task",
    subject: "Review Peterson contract",
    description: "Review annual maintenance contract terms and pricing.",
    leadId: "lead-1",
    contactId: "contact-1",
    opportunityId: "opportunity-1",
    accountId: "account-1",
    ownerId: DEMO_USER_ID,
    dueDate: new Date("2025-01-10"),
    completed: true,
  },
];
